# Generated by Django 5.1.4 on 2026-04-24 19:59

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=200, verbose_name='Société')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('address', models.TextField(blank=True, verbose_name='Adresse')),
                ('vat_number', models.CharField(blank=True, max_length=30, verbose_name='Numéro TVA')),
                ('notes', models.TextField(blank=True, verbose_name='Notes internes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Référence')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('sent', 'Envoyé'), ('accepted', 'Accepté'), ('refused', 'Refusé'), ('expired', 'Expiré')], default='draft', max_length=20, verbose_name='Statut')),
                ('valid_until', models.DateField(verbose_name="Valable jusqu'au")),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='devis/', verbose_name='PDF')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devis', to='clients.client', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Devis',
                'verbose_name_plural': 'Devis',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DevisLigne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300, verbose_name='Description')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=8, verbose_name='Quantité')),
                ('unit_price_excl', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix unitaire HTVA')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=Decimal('21.00'), max_digits=5, verbose_name='TVA %')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Ordre')),
                ('devis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='clients.devis')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Référence')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('paid', 'Payée'), ('overdue', 'En retard'), ('cancelled', 'Annulée')], default='pending', max_length=20, verbose_name='Statut')),
                ('due_date', models.DateField(verbose_name='Échéance')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Payée le')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='factures/', verbose_name='PDF')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='clients.client', verbose_name='Client')),
                ('devis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures', to='clients.devis', verbose_name='Devis lié')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompteTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200, verbose_name='Libellé')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Positif = crédit, négatif = débit', max_digits=10, verbose_name='Montant')),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Solde après')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='clients.client', verbose_name='Client')),
                ('related_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.facture', verbose_name='Facture liée')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='FactureLigne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300, verbose_name='Description')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=8, verbose_name='Quantité')),
                ('unit_price_excl', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix unitaire HTVA')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=Decimal('21.00'), max_digits=5, verbose_name='TVA %')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Ordre')),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='clients.facture')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('scheduled_at', models.DateTimeField(verbose_name='Planifiée le')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Effectuée le')),
                ('status', models.CharField(choices=[('scheduled', 'Planifiée'), ('completed', 'Effectuée'), ('cancelled', 'Annulée'), ('rescheduled', 'Reportée')], default='scheduled', max_length=20, verbose_name='Statut')),
                ('technician', models.CharField(blank=True, max_length=100, verbose_name='Technicien')),
                ('notes', models.TextField(blank=True, verbose_name="Rapport d'intervention")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance', to='clients.client', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Maintenance',
                'verbose_name_plural': 'Maintenances',
                'ordering': ['scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='Prestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('start_date', models.DateField(verbose_name='Début')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fin')),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Suspendue'), ('completed', 'Terminée'), ('cancelled', 'Annulée')], default='active', max_length=20, verbose_name='Statut')),
                ('annual_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix annuel')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestations', to='clients.client', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Prestation',
                'verbose_name_plural': 'Prestations',
                'ordering': ['-start_date'],
            },
        ),
    ]
