# Generated by Django 5.1.4 on 2026-04-29 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='comptetransaction',
            index=models.Index(fields=['client', '-date'], name='transaction_client_date_idx'),
        ),
        migrations.AddIndex(
            model_name='devis',
            index=models.Index(fields=['client', 'status'], name='devis_client_status_idx'),
        ),
        migrations.AddIndex(
            model_name='devis',
            index=models.Index(fields=['client', '-created_at'], name='devis_client_date_idx'),
        ),
        migrations.AddIndex(
            model_name='facture',
            index=models.Index(fields=['client', 'status'], name='facture_client_status_idx'),
        ),
        migrations.AddIndex(
            model_name='facture',
            index=models.Index(fields=['client', 'due_date'], name='facture_client_due_date_idx'),
        ),
        migrations.AddIndex(
            model_name='facture',
            index=models.Index(fields=['client', '-created_at'], name='facture_client_date_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenance',
            index=models.Index(fields=['client', 'status', 'scheduled_at'], name='maint_client_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='prestation',
            index=models.Index(fields=['client', 'status'], name='prestation_client_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='devisligne',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='devis_ligne_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='devisligne',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price_excl__gte', 0)), name='devis_ligne_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='factureligne',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='facture_ligne_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='factureligne',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price_excl__gte', 0)), name='facture_ligne_price_non_negative'),
        ),
    ]
